# Generated by Django 4.2.1 on 2023-11-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_mediafiles', '0002_alter_image_date_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='поное название', max_length=200, verbose_name='должность')),
                ('full_name', models.SlugField(max_length=250, unique=True, verbose_name='полное имя')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.image', verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'руководитель',
                'verbose_name_plural': 'руководители',
            },
        ),
    ]
