# Generated by Django 4.2.1 on 2023-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='full_name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='полное имя'),
        ),
    ]
