# Generated by Django 4.2.1 on 2023-11-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0006_alter_objectgallery_obj'),
        ('app_about', '0002_alter_manager_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='поное название', max_length=200, verbose_name='должность')),
                ('full_name', models.TextField(db_index=True, max_length=250, verbose_name='описание требований')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_objects.object', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'вакантные места',
            },
        ),
    ]
