# Generated by Django 4.2.1 on 2023-12-01 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0005_wp_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wp_page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 14, 22, 19, 127607, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='wp_page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_about.wp_page', verbose_name='родительская страница'),
        ),
    ]
