# Generated by Django 4.2.1 on 2023-12-02 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0007_remove_wp_page_status_alter_wp_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wp_page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 9, 36, 26, 367719, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
