# Generated by Django 4.2.1 on 2023-12-03 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0009_document_content_type_document_old_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wp_page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 7, 50, 1, 604024, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
