# Generated by Django 4.2.1 on 2023-12-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_about', '0011_alter_wp_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wp_page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 10, 17, 48, 408684, tzinfo=datetime.timezone.utc), verbose_name='дата создания'),
        ),
    ]
