# Generated by Django 4.2.1 on 2023-11-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=65, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=50, null=True, verbose_name="email"
                    ),
                ),
                (
                    "obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="app_objects.object",
                        verbose_name="объект",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_objects.sportarea",
                        verbose_name="ресурс",
                    ),
                ),
            ],
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты",},
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="отображаемый", max_length=20, verbose_name="телефон"
                    ),
                ),
                (
                    "phone_url",
                    models.CharField(
                        default="+7",
                        help_text="согласно e164",
                        max_length=16,
                        verbose_name="телефон",
                    ),
                ),
                (
                    "phone_add",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="добавочный"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_contacts.contact",
                        verbose_name="контакт",
                    ),
                ),
            ],
            options={"verbose_name": "Телефон", "verbose_name_plural": "Телефоны",},
        ),
    ]
