# Generated by Django 4.2.1 on 2023-05-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
