# Generated by Django 4.2.1 on 2023-11-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0004_remove_sportareagallery_photos_and_more'),
        ('app_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='stock',
        ),
        migrations.AddField(
            model_name='contact',
            name='sportarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.sportarea', verbose_name='спортплощадка'),
        ),
    ]
