# Generated by Django 4.2.1 on 2023-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contacts', '0002_remove_contact_obj_remove_contact_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default='администратор', help_text='кому попадем', max_length=22, verbose_name='пояснение'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_url',
            field=models.CharField(default='+7', help_text='согласно e164 (ссылка)', max_length=16, verbose_name='телефон'),
        ),
    ]
