# Generated by Django 4.2.1 on 2023-11-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0004_remove_sportareagallery_photos_and_more'),
        ('app_contacts', '0004_alter_contact_sportarea_alter_phone_phone_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sportarea',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='app_objects.sportarea', verbose_name='спортплощадка'),
        ),
    ]
