# Generated by Django 4.2.1 on 2023-11-04 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_tags", "0001_initial"),
        ("app_mediafiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "date_public",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата публикации"
                    ),
                ),
                ("title", models.CharField(max_length=110, verbose_name="заголовок")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=550, null=True, verbose_name="отрывок"
                    ),
                ),
                (
                    "content",
                    models.TextField(max_length=2500, verbose_name="содержание"),
                ),
                (
                    "important",
                    models.BooleanField(default=False, verbose_name="на первую полосу"),
                ),
                (
                    "valid_until_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="действует до"
                    ),
                ),
                (
                    "date_activation",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="дата активации"
                    ),
                ),
                (
                    "featured_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_mediafiles.image",
                        verbose_name="id media",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="app_tags.tag")),
            ],
            options={"verbose_name": "новость", "verbose_name_plural": "новости",},
        ),
    ]
