# Generated by Django 4.2.1 on 2023-06-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0005_alter_image_img_mode"),
        ("app_news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "новость", "verbose_name_plural": "новости"},
        ),
        migrations.AlterField(
            model_name="news",
            name="featured_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_mediafiles.image",
                verbose_name="id media",
            ),
        ),
        migrations.DeleteModel(name="ImageMedia",),
    ]
