# Generated by Django 4.2.1 on 2023-11-21 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0002_alter_image_date_public'),
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_public',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='app_mediafiles.image', verbose_name='id media'),
        ),
    ]
