# Generated by Django 4.2.1 on 2023-11-18 09:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='compose_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='level_importance',
            field=models.CharField(choices=[('danger', 'важный'), ('warning', 'предупреждение'), ('info', 'информация')], default='info', max_length=8),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=3500, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_public',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=210, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=210, verbose_name='заголовок'),
        ),
    ]
