# Generated by Django 4.2.1 on 2023-11-21 08:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_alter_news_date_public_alter_news_featured_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3500, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='important',
            field=models.BooleanField(default=False, verbose_name='важная'),
        ),
    ]
