# Generated by Django 4.2.1 on 2023-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_news", "0002_alter_news_options_alter_news_featured_media_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(max_length=2500, verbose_name="содержание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="date_public",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="excerpt",
            field=models.TextField(
                blank=True, max_length=550, null=True, verbose_name="отрывок"
            ),
        ),
        migrations.AlterField(
            model_name="news", name="slug", field=models.SlugField(max_length=110),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=110, verbose_name="заголовок"),
        ),
    ]
