# Generated by Django 4.2.1 on 2023-11-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_alter_news_content_alter_news_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='level_importance',
            field=models.CharField(choices=[('danger', 'важный'), ('warning', 'предупреждение'), ('info', 'информация')], default='info', max_length=8, verbose_name='уровень важности'),
        ),
    ]
