# Generated by Django 4.2.1 on 2023-06-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tags", "0002_alter_tag_table"),
        ("app_news", "0004_alter_news_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="important",
            field=models.BooleanField(default=False, verbose_name="на первую полосу"),
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, to="app_tags.tag"),
        ),
        migrations.AddField(
            model_name="news",
            name="valid_until_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="действует до"
            ),
        ),
    ]
