# Generated by Django 4.2.1 on 2023-06-23 16:46

import app_mediafiles.models
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='иконка ...', help_text='иконка бассейна, иконка стадиона и пр.', max_length=60)),
                ('image', models.ImageField(upload_to=app_mediafiles.models.path_icon_file)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='высота')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='заголовок')),
                ('caption', models.TextField(max_length=260, verbose_name='подпись-описание')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='часть url')),
                ('alt_txt', models.CharField(default='fill necessarily! ', max_length=90, verbose_name='альтернативная подпись')),
                ('date_public', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('img_file_size', models.IntegerField(blank=True, null=True, verbose_name='объем файла')),
                ('img_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='высота')),
                ('media_type', models.CharField(blank=True, help_text='расширение файла', max_length=5, null=True, verbose_name='расширение')),
                ('image', models.ImageField(upload_to=app_mediafiles.models.path_photo_file, verbose_name='файл картинки')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('imagelibrary/photo/thumbnail'), verbose_name='миниатюра самая маленькая')),
                ('medium', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('imagelibrary/photo/middle'), verbose_name='миниатюра средняя')),
                ('large', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('imagelibrary/photo/large'), verbose_name='миниатюра большая')),
                ('tags', models.ManyToManyField(blank=True, to='app_tags.tag')),
            ],
            options={
                'verbose_name': 'Изобажение',
                'verbose_name_plural': 'Галерея изображений',
            },
        ),
    ]
