# Generated by Django 4.2.1 on 2023-05-17 12:33

import app_mediafiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='иконка ...', max_length=60)),
                ('image', models.ImageField(upload_to=app_mediafiles.models.path_icon_file)),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
    ]
