# Generated by Django 4.2.1 on 2023-05-19 14:41

import app_mediafiles.models
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='иконка ...', help_text='иконка бассейна, иконка стадиона и пр.', max_length=60)),
                ('image', models.ImageField(upload_to=app_mediafiles.models.path_icon_file)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='высота')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название (alt)')),
                ('description', models.TextField(max_length=260, verbose_name='описание')),
                ('image', models.ImageField(upload_to=app_mediafiles.models.path_photo_file, verbose_name='файл картинки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='высота')),
                ('thumbnail_middle', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('imagelibrary/photo/thumbnail_middle'), verbose_name='средняя миниатюра')),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('imagelibrary/photo/thumbnail_small'), verbose_name='миниминиатюра')),
                ('tags', models.ManyToManyField(blank=True, to='app_mediafiles.tag')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
