# Generated by Django 4.2.1 on 2023-06-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField('Image', 'name', 'title'),
        migrations.RenameField('Image', 'description', 'caption'),
        migrations.RenameField('Image', 'created', 'date_public'),
        migrations.RenameField('Image', 'thumbnail_middle', 'medium'),
        migrations.RenameField('Image', 'thumbnail_small', 'thumbnail'),
    ]
