# Generated by Django 4.2.1 on 2023-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_public',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки'),
        ),
    ]
