# Generated by Django 4.2.1 on 2023-06-20 04:13

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0002_auto_20230620_1137"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изобажение",
                "verbose_name_plural": "Галерея изображений",
            },
        ),
        migrations.AddField(
            model_name="image",
            name="alt_txt",
            field=models.CharField(
                default="fill necessarily! ",
                max_length=70,
                verbose_name="альтернативная подпись",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="img_file_size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="объем файла"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="img_mode",
            field=models.CharField(
                blank=True, help_text="color, grey, and other", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="large",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath("imagelibrary/photo/large"),
                verbose_name="миниатюра большая",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="media_type",
            field=models.CharField(
                blank=True,
                help_text="расширение файла",
                max_length=5,
                null=True,
                verbose_name="расширение",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="slug",
            field=models.SlugField(
                default="fill necessarily! ", max_length=70, verbose_name="часть url"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.TextField(max_length=160, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="image",
            name="medium",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath("imagelibrary/photo/middle"),
                verbose_name="миниатюра средняя",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath("imagelibrary/photo/thumbnail"),
                verbose_name="миниатюра самая маленькая",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=70, verbose_name="заголовок"),
        ),
    ]
