# Generated by Django 4.2.1 on 2023-05-18 11:00

import app_mediafiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0002_tag_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_middle',
            field=models.ImageField(blank=True, null=True, upload_to=app_mediafiles.models.path_photo_file),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to=app_mediafiles.models.path_photo_file),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=app_mediafiles.models.path_photo_file),
        ),
    ]
