# Generated by Django 4.2.1 on 2023-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0003_alter_image_options_image_thumbnail_middle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_middle',
            field=models.ImageField(blank=True, null=True, upload_to='imagelibrary/photo/thumbnail_middle'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='imagelibrary/photo/thumbnail_small'),
        ),
    ]
