# Generated by Django 4.2.1 on 2023-06-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0003_alter_image_options_image_alt_txt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alt_txt",
            field=models.CharField(
                default="fill necessarily! ",
                max_length=90,
                verbose_name="альтернативная подпись",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.TextField(max_length=260, verbose_name="подпись-описание"),
        ),
        migrations.AlterField(
            model_name="image",
            name="slug",
            field=models.SlugField(
                default="fill necessarily! ", max_length=90, verbose_name="часть url"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=90, verbose_name="заголовок"),
        ),
    ]
