# Generated by Django 4.2.1 on 2023-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0004_alter_image_alt_txt_alter_image_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="img_mode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
