# Generated by Django 4.2.1 on 2023-05-18 14:52

import app_mediafiles.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0004_alter_image_thumbnail_middle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='высота'),
        ),
        migrations.AddField(
            model_name='icon',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='ширина'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(default='иконка ...', help_text='иконка бассейна, иконка стадиона и пр.', max_length=60),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=app_mediafiles.models.path_photo_file, verbose_name='файл картинки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_middle',
            field=models.ImageField(blank=True, null=True, upload_to='imagelibrary/photo/thumbnail_middle', verbose_name='средняя миниатюра'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='imagelibrary/photo/thumbnail_small', verbose_name='миниминиатюра'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='ширина'),
        ),
    ]
