# Generated by Django 4.2.1 on 2023-06-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0005_alter_image_img_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="slug",
            field=models.SlugField(
                max_length=90, unique=True, verbose_name="часть url"
            ),
        ),
    ]
