# Generated by Django 4.2.1 on 2023-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='метка'),
        ),
    ]
