# Generated by Django 4.2.1 on 2023-06-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="tag", table=None,),
    ]
