# Generated by Django 4.2.1 on 2023-05-19 14:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название услуги')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, verbose_name='краткое описание')),
                ('category', models.CharField(choices=[('sport', 'Спортивные услуги'), ('section', 'Спортивные секции'), ('other', 'Прочие услуги')], max_length=10, verbose_name='категория услуги')),
                ('slug', models.SlugField(blank=True, help_text='только латинские буквы и цифры', max_length=60, null=True, unique=True, verbose_name='slug имя в url')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='файл иконки')),
                ('photo', models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='services', verbose_name='файл фотографии')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='TypeSportForMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название типа спорта')),
                ('slug', models.CharField(max_length=60, verbose_name='название на английском')),
                ('order', models.SmallIntegerField(default=255, verbose_name='сортировка')),
                ('icon', models.ImageField(upload_to='menu/typesport', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Тип спорта',
                'verbose_name_plural': 'Типы спорта',
            },
        ),
        migrations.CreateModel(
            name='VariousSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название спорта')),
                ('slug', models.CharField(max_length=60, verbose_name='название на английском')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
    ]
