# Generated by Django 4.2.1 on 2023-11-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeservicegallery",
            name="typeservice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photo",
                to="app_services.typeservice",
                verbose_name="Услуга",
            ),
        ),
    ]
