# Generated by Django 4.2.1 on 2023-05-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSportForMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название типа спорта')),
                ('slug', models.CharField(max_length=60, verbose_name='название на английском')),
                ('order', models.SmallIntegerField(default=255, verbose_name='сортировка')),
                ('icon', models.ImageField(upload_to='menu/typesport', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
    ]
