# Generated by Django 4.2.1 on 2023-05-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='typesportformenu',
            name='icon',
        ),
    ]
