# Generated by Django 4.2.1 on 2023-08-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=100, verbose_name='важность'),
        ),
    ]
