# Generated by Django 4.2.1 on 2023-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='только латинские буквы и цифры', max_length=60, null=True, unique=True, verbose_name='slug имя в url'),
        ),
    ]
