# Generated by Django 4.2.1 on 2023-05-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservice',
            name='category',
            field=models.CharField(choices=[('sport', 'Спортивные услуги'), ('section', 'Спортивные секции'), ('relax', 'Отдых'), ('other', 'Прочие услуги')], default='other', max_length=10, verbose_name='категория услуги'),
        ),
    ]
