# Generated by Django 4.2.1 on 2023-05-23 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.image', verbose_name='фотографии')),
                ('typeservice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.typeservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Галерея фотографий услуги',
                'verbose_name_plural': 'Галерея фотографий услуг',
            },
        ),
        migrations.DeleteModel(
            name='ServiceGallery',
        ),
    ]
