# Generated by Django 4.2.1 on 2023-11-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0002_alter_image_date_public'),
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeservicegallery',
            options={'verbose_name': 'Фотография вида услуг', 'verbose_name_plural': 'Галерея фотографий'},
        ),
        migrations.RemoveField(
            model_name='typeservicegallery',
            name='photos',
        ),
        migrations.AlterField(
            model_name='typeservicegallery',
            name='typeservice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_services.typeservice', verbose_name='тип услуги'),
        ),
        migrations.AddField(
            model_name='typeservicegallery',
            name='photos',
            field=models.ManyToManyField(to='app_mediafiles.image', verbose_name='фотографии'),
        ),
    ]
