# Generated by Django 4.2.1 on 2023-05-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
        ('app_services', '0002_remove_service_icon_remove_service_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesportformenu',
            name='icon',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.icon', verbose_name='иконка'),
        ),
    ]
