# Generated by Django 4.2.1 on 2023-11-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0006_alter_objectgallery_obj'),
        ('app_services', '0002_alter_typeservicegallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sportarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_objects.sportarea', verbose_name='спортплощадка'),
        ),
    ]
