# Generated by Django 4.2.1 on 2023-05-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_typesportformenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typesportformenu',
            options={'verbose_name': 'Тип спорта', 'verbose_name_plural': 'Типы спорта'},
        ),
    ]
