# Generated by Django 4.2.1 on 2023-08-13 09:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_service_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2500, verbose_name='краткое описание'),
        ),
    ]
