# Generated by Django 4.2.1 on 2023-06-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_typeservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservice',
            name='description',
            field=models.TextField(default='необходимо заполнить', help_text='кратко описываем группу услуг', max_length=200, verbose_name='Описание группы услуг'),
        ),
    ]
