# Generated by Django 4.2.1 on 2023-05-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_service_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descriprion',
            new_name='description',
        ),
    ]
