# Generated by Django 4.2.1 on 2023-05-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_typeservicegallery_delete_servicegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeservicegallery',
            options={'verbose_name': 'Фотография вида услуг', 'verbose_name_plural': 'Галерея фотографий услуг'},
        ),
    ]
