# Generated by Django 4.2.1 on 2023-11-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_mediafiles", "0001_initial"),
        ("app_services", "0002_alter_typeservicegallery_typeservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeservicegallery",
            name="photos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service",
                to="app_mediafiles.image",
                verbose_name="фотографии",
            ),
        ),
    ]
