# Generated by Django 4.2.1 on 2023-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0003_rename_descriprion_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='пиктограмка услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='services', verbose_name='фотография услуги'),
        ),
    ]
