# Generated by Django 4.2.1 on 2023-08-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0002_object_call_center'),
        ('app_services', '0003_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_objects.object', verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='только латинские буквы и цифры', max_length=120, null=True, unique=True, verbose_name='slug имя в url'),
        ),
    ]
