# Generated by Django 4.2.1 on 2023-05-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
        ('app_services', '0003_typesportformenu_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название группы услуг')),
                ('slug', models.CharField(max_length=60, verbose_name='название на английском')),
                ('order', models.SmallIntegerField(default=255, verbose_name='сортировка')),
                ('icon', models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.icon', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.DeleteModel(
            name='TypeSportForMenu',
        ),
    ]
