# Generated by Django 4.2.1 on 2023-11-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0003_service_sportarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
