# Generated by Django 4.2.1 on 2023-12-05 10:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0004_remove_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2500, null=True, verbose_name='краткое описание'),
        ),
    ]
