# Generated by Django 4.2.1 on 2023-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0004_service_icon_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Spt', 'Спортивные услуги'), ('Sec', 'Спортивные секции'), ('Oth', 'Прочие услуги')], max_length=4, verbose_name='категория услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='файл иконки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='services', verbose_name='файл фотографии'),
        ),
    ]
