# Generated by Django 4.2.1 on 2023-08-19 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0005_alter_typestock_name'),
        ('app_services', '0004_service_object_alter_service_name_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_objects.object', verbose_name='объект'),
        ),
    ]
