# Generated by Django 4.2.1 on 2023-05-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0004_typeservice_delete_typesportformenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='typeservice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_services.typeservice', verbose_name='группа услуг'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='name',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Название группы услуг'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='slug',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='название на английском'),
        ),
        migrations.AlterField(
            model_name='varioussport',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название спорта'),
        ),
        migrations.AlterField(
            model_name='varioussport',
            name='slug',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='название на английском'),
        ),
    ]
