# Generated by Django 4.2.1 on 2023-11-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0004_rate_promotion_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
