# Generated by Django 4.2.1 on 2023-05-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
        ('app_services', '0005_service_typeservice_alter_typeservice_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.service', verbose_name='Объект')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.image', verbose_name='фотографии')),
            ],
            options={
                'verbose_name': 'Галерея фотографий услуги',
                'verbose_name_plural': 'Галерея фотографий услуг',
            },
        ),
    ]
