# Generated by Django 4.2.1 on 2023-11-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0005_alter_discount_discount_value_alter_rate_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name": "дискаунт", "verbose_name_plural": "дискаунты"},
        ),
        migrations.RemoveField(model_name="rate", name="forchild",),
        migrations.AddField(
            model_name="rate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rate", name="name", field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="rate",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
