# Generated by Django 4.2.1 on 2023-05-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0005_alter_service_category_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('sport', 'Спортивные услуги'), ('section', 'Спортивные секции'), ('other', 'Прочие услуги')], max_length=10, verbose_name='категория услуги'),
        ),
    ]
