# Generated by Django 4.2.1 on 2023-08-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0005_alter_typestock_name'),
        ('app_services', '0005_alter_service_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='typestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_services', to='app_objects.typestock', verbose_name='ресурс'),
        ),
    ]
