# Generated by Django 4.2.1 on 2023-05-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0006_servicegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegallery',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_services.service', verbose_name='Услуга'),
        ),
    ]
