# Generated by Django 4.2.1 on 2023-11-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0006_alter_discount_options_remove_rate_forchild_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name": "дисконт", "verbose_name_plural": "дисконты"},
        ),
        migrations.RenameField(
            model_name="discount", old_name="discount_type", new_name="type",
        ),
        migrations.RenameField(
            model_name="discount", old_name="discount_value", new_name="value",
        ),
    ]
