# Generated by Django 4.2.1 on 2023-05-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0006_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariousSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название спорта')),
                ('slug', models.CharField(max_length=60, verbose_name='название на английском')),
            ],
        ),
    ]
