# Generated by Django 4.2.1 on 2023-05-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0007_varioussport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varioussport',
            options={'verbose_name': 'Вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
    ]
