# Generated by Django 4.2.1 on 2023-11-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_services",
            "0008_remove_service_object_remove_service_sportarea_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="forchild",
            field=models.BooleanField(default=False),
        ),
    ]
