# Generated by Django 4.2.1 on 2023-11-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_services", "0009_discount_forchild"),
    ]

    operations = [
        migrations.RemoveField(model_name="discount", name="forchild",),
    ]
