# Generated by Django 4.2.1 on 2023-05-25 00:11

import app_booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subunitbooking',
            options={'verbose_name': 'бронирование ресурса', 'verbose_name_plural': 'забронированные ресурсы'},
        ),
        migrations.AlterField(
            model_name='subunitbooking',
            name='time_slot',
            field=models.JSONField(default=app_booking.models.json_default_value, verbose_name='время начала и конца бронирования'),
        ),
    ]
