# Generated by Django 4.2.1 on 2023-05-14 09:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Короткое имя объекта (не более 15 символов)', max_length=15, verbose_name='краткое имя')),
                ('name', models.CharField(help_text='Полное официальное имя (не более 250  символов)', max_length=250, verbose_name='официальное имя')),
                ('slug', models.SlugField(help_text='только латинские буквы и цифры', max_length=15, unique=True, verbose_name='slug имя в url')),
                ('address', models.CharField(help_text='Адрес по форме город, улица, дом', max_length=200, verbose_name='адрес')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='краткое описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='objects', verbose_name='пиктограмка')),
                ('photo', models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='objects', verbose_name='фотография объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='стадион, универсальный зал и пр.', max_length=25, verbose_name='название')),
                ('slug', models.SlugField(help_text='желательно английское название', max_length=25, unique=True, verbose_name='slug имя в url')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='objects', verbose_name='пиктограмка')),
            ],
            options={
                'verbose_name': 'Спортивный ресурс',
                'verbose_name_plural': 'Спортивные ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='подразделение, отдел, направление', max_length=35, verbose_name='название конкретного ресурса')),
                ('slug', models.SlugField(help_text='только латинские буквы и цифры', max_length=35, unique=True, verbose_name='slug имя в url')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание подразделения, характеристики')),
                ('photo', models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='objects', verbose_name='фотография')),
                ('contact', models.CharField(help_text='по сути объект с названием типом связи и пр. возможно несколько', max_length=25, verbose_name='Телефон')),
                ('shedule', models.CharField(help_text='режим работы, график, сан. день (как календарь)', max_length=25, verbose_name='график работы')),
                ('obj', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.object', verbose_name='Объект')),
                ('resource', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.resource', verbose_name='спортивный ресурс')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
    ]
