# Generated by Django 4.2.1 on 2023-05-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Короткое имя объекта (не более 15 символов)', max_length=15, verbose_name='краткое имя')),
                ('name', models.CharField(help_text='Ролное официальное имя (не более 250  символов)', max_length=250, verbose_name='официальное имя')),
                ('address', models.CharField(help_text='Адрес совместимый с GeoAPI', max_length=200, verbose_name='адрес')),
                ('contacts', models.CharField(max_length=200, verbose_name='контакты')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
