# Generated by Django 4.2.1 on 2023-11-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0002_alter_image_date_public'),
        ('app_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectgallery',
            options={'verbose_name': 'фотография объекта', 'verbose_name_plural': 'фотографии объектов'},
        ),
        migrations.RemoveField(
            model_name='objectgallery',
            name='area',
        ),
        migrations.AlterField(
            model_name='objectgallery',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.image', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='sportarea',
            name='inviting_mes',
            field=models.CharField(default='призывной призыв или слоган', max_length=90, verbose_name='слоган или призыв к посещению'),
        ),
        migrations.CreateModel(
            name='SportAreaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.image', verbose_name='фотография')),
                ('sportarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.sportarea', verbose_name='спортплощадка')),
            ],
            options={
                'verbose_name': 'фотография спортплощадки',
                'verbose_name_plural': 'фотографии спортплощадок',
            },
        ),
    ]
