# Generated by Django 4.2.1 on 2023-11-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_objects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typestock",
            options={
                "verbose_name": "спортплощадка",
                "verbose_name_plural": "спортплощадки",
            },
        ),
        migrations.AlterField(
            model_name="typestock",
            name="name",
            field=models.CharField(
                help_text="бассейн, стадион, тренажерный зал, универсальный зал и пр.",
                max_length=35,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="typestock",
            name="obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sportarea",
                to="app_objects.object",
                verbose_name="Объект",
            ),
        ),
    ]
