# Generated by Django 4.2.1 on 2023-05-16 04:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typestock',
            name='order',
            field=models.IntegerField(default=100, verbose_name='сортировка'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=3000, null=True, verbose_name='краткое описание'),
        ),
    ]
