# Generated by Django 4.2.1 on 2023-05-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='type_stock',
            field=models.ManyToManyField(help_text='имеющиеся на объекте типы ресурсов', to='app_objects.typestock', verbose_name='группа ресурсов'),
        ),
    ]
