# Generated by Django 4.2.1 on 2023-11-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectgallery",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_objects.sportarea",
                verbose_name="спортплощадка",
            ),
        ),
        migrations.DeleteModel(name="Subunit",),
    ]
