# Generated by Django 4.2.1 on 2023-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='call_center',
            field=models.CharField(default='+7(3012) 5-30-36', max_length=20, verbose_name='номер телефона'),
        ),
    ]
