# Generated by Django 4.2.1 on 2023-11-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_objects", "0002_alter_typestock_options_alter_typestock_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="square",
            field=models.CharField(default="-", max_length=11, verbose_name="площадь"),
        ),
        migrations.AddField(
            model_name="object",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата ввода в эксплуатацию"
            ),
        ),
    ]
