# Generated by Django 4.2.1 on 2023-05-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
        ('app_objects', '0002_alter_typestock_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_objects.object', verbose_name='Объект')),
                ('photos', models.ManyToManyField(blank=True, null=True, to='app_mediafiles.image', verbose_name='фотографии')),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
    ]
