# Generated by Django 4.2.1 on 2023-05-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0002_object_type_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectgallery',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery', to='app_objects.object', verbose_name='Объект'),
        ),
    ]
