# Generated by Django 4.2.1 on 2023-11-02 13:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_objects", "0003_object_square_object_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="typestock",
            name="characteristics",
            field=models.JSONField(
                blank=True, null=True, verbose_name="характеристики спортплощадки"
            ),
        ),
        migrations.AddField(
            model_name="typestock",
            name="inviting_mes",
            field=models.TextField(
                default="призывной призыв или слоган",
                max_length=90,
                verbose_name="слоган или призыв к посещению",
            ),
        ),
        migrations.AlterField(
            model_name="typestock",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="",
                help_text="описание спортплощадки без характеристик и расписания",
                max_length=1500,
                verbose_name="краткое описание",
            ),
        ),
    ]
