# Generated by Django 4.2.1 on 2023-05-21 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mediafiles', '0001_initial'),
        ('app_objects', '0003_objectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectphoto',
            name='photos',
            field=models.ManyToManyField(blank=True, to='app_mediafiles.image', verbose_name='фотографии'),
        ),
        migrations.CreateModel(
            name='ObjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_objects.object', verbose_name='Объект')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_mediafiles.image', verbose_name='фотографии')),
            ],
            options={
                'verbose_name': 'Галерея фотографий объекта',
                'verbose_name_plural': 'Галереи фотографий объектов',
            },
        ),
    ]
