# Generated by Django 4.2.1 on 2023-08-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0003_remove_object_type_stock_typestock_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestock',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='typestocks', to='app_objects.object', verbose_name='Объект'),
        ),
    ]
