# Generated by Django 4.2.1 on 2023-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0003_alter_object_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(help_text='Полное официальное имя (не более 250  символов)', max_length=250, verbose_name='официальное имя'),
        ),
    ]
