# Generated by Django 4.2.1 on 2023-11-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0004_remove_sportareagallery_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='call_center',
            field=models.CharField(default='+7(3012)', max_length=20, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='sportareagallery',
            name='sportarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_objects.sportarea', unique=True, verbose_name='спортплощадка'),
        ),
    ]
