# Generated by Django 4.2.1 on 2023-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0004_alter_typestock_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestock',
            name='name',
            field=models.CharField(help_text='стадион, универсальный зал и пр. без конкретики', max_length=35, verbose_name='название'),
        ),
    ]
