# Generated by Django 4.2.1 on 2023-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0004_rename_descriprion_object_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='objects', verbose_name='пиктограмка'),
        ),
        migrations.AddField(
            model_name='object',
            name='photo',
            field=models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='objects', verbose_name='фотография объекта'),
        ),
    ]
