# Generated by Django 4.2.1 on 2023-12-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0006_alter_objectgallery_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_header',
            field=models.BooleanField(default=False, verbose_name='головная организация'),
        ),
    ]
