# Generated by Django 4.2.1 on 2023-05-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0006_subunit_object_subunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subunit',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
