# Generated by Django 4.2.1 on 2023-05-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0007_alter_subunit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='subunit',
        ),
        migrations.AddField(
            model_name='subunit',
            name='obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.object', verbose_name='Объект'),
        ),
    ]
