# Generated by Django 4.2.1 on 2023-05-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0008_remove_object_subunit_subunit_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunit',
            name='obj',
        ),
        migrations.AddField(
            model_name='subunit',
            name='obj',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='app_objects.object', verbose_name='Объект'),
        ),
    ]
