# Generated by Django 4.2.1 on 2023-05-14 06:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0009_remove_subunit_obj_subunit_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='стадион, универсальный зал и пр.', max_length=25, verbose_name='название')),
                ('slug', models.SlugField(help_text='желательно английское название', max_length=25, unique=True, verbose_name='slug имя в url')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Описание в общем случае')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='objects', verbose_name='пиктограмка')),
            ],
            options={
                'verbose_name': 'Спортивный ресурс',
                'verbose_name_plural': 'Спортивные ресурсы',
            },
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='icon',
        ),
        migrations.AlterField(
            model_name='subunit',
            name='name',
            field=models.CharField(help_text='подразделение, отдел, направление', max_length=25, verbose_name='название конкретного ресурса'),
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='obj',
        ),
        migrations.AddField(
            model_name='subunit',
            name='resource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.resource'),
        ),
        migrations.AddField(
            model_name='subunit',
            name='obj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.object', verbose_name='Объект'),
        ),
    ]
