# Generated by Django 4.2.1 on 2023-05-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0010_resource_remove_subunit_icon_alter_subunit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
    ]
