# Generated by Django 4.2.1 on 2023-05-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_objects', '0011_remove_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunit',
            name='name',
            field=models.CharField(help_text='подразделение, отдел, направление', max_length=35, verbose_name='название конкретного ресурса'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='photo',
            field=models.ImageField(blank=True, help_text='в будущем набор фотографий для слайдера', null=True, upload_to='objects', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='resource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_objects.resource', verbose_name='спортивный ресурс'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='slug',
            field=models.SlugField(help_text='только латинские буквы и цифры', max_length=35, unique=True, verbose_name='slug имя в url'),
        ),
    ]
